modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "origins_plus_plus"
version = "${version}"
displayName = "Origins++"
description = "A collection of 115 origins to fully expand the origins experience."

displayURL = "https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus"
issueTrackerURL = "https://github.com/QuantumXenon/origins-plus-plus/issues"
authors = "TheQuantumXenon"
credits = "Credit goes to original authors (see CurseForge description)"
logoFile = "icon.png"

[[dependencies.origins_plus_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"

[[dependencies.origins_plus_plus]]
modId = "origins"
mandatory = true
versionRange = "[1.18.2-1.4.1.4,)"

[[dependencies.origins_plus_plus]]
modId = "pehkui"
mandatory = true
versionRange = "[3.2.0,)"

[[dependencies.origins_plus_plus]]
modId = "xl_packets_renewed"
mandatory = true
versionRange = "[1.3,)"