modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="origins_plus_plus"
version="${version}"
displayName="Origins++"
description='A collection of 115 origins'

displayURL="https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus"
issueTrackerURL="https://github.com/QuantumXenon/origins-plus-plus/issues"
authors="TheQuantumXenon"
credits="Credit goes to original authors (see CurseForge description)"
logoFile="assets/icon.png"

[[dependencies.origins_plus_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"

[[dependencies.origins_plus_plus]]
    modId="origins"
    mandatory=true
    versionRange="[1.19.2-1.5.0.6,)"
	
[[dependencies.origins_plus_plus]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.3.3,)"