# The name of the mod loader type to load (#mandatory)
modLoader="javafml"

# A version range to match for said mod loader (#mandatory)
loaderVersion="[40,)"

# The license for your mod (#mandatory)
license="MIT"

# A list of mods (#mandatory)
[[mods]] 

# The modId of the mod (#mandatory)
modId="origins_plus_plus"

# The version number of the mod (#mandatory)
version="1.7"

 # A display name for the mod (#mandatory)
displayName="Origins++"

# The description text for the mod (#mandatory)
description='A collection of 115 origins'

displayURL="https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus"
issueTrackerURL="https://github.com/QuantumXenon/origins-plus-plus/issues"
authors="TheQuantumXenon"
credits="Credit goes to original authors (see CurseForge description)"
logoFile="icon.png"

[[dependencies.origins_plus_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.origins_plus_plus]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins_plus_plus]]
    modId="apoli"
    mandatory=true
    versionRange="[1.18.2-1.4.1.4,)"
    ordering="NONE"
    side="BOTH"	
	
[[dependencies.origins_plus_plus]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.2.0,)"
    ordering="NONE"
    side="BOTH"