name: Update Submodule
'on':
  push:
    branches:
      - main
jobs:
  update-fabric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: QuantumXenon/origins-plus-plus-fabric
          token: '${{secrets.TOKEN}}'
          submodules: true
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "Update Origins++ Submodule"
          git push
  update-forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: QuantumXenon/origins-plus-plus-forge
          token: '${{secrets.TOKEN}}'
          submodules: true
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add --all
          git commit -m "Update Origins++ Submodule"
          git push
